sharding:
    jdbc:
        masters:
            - master:
                name: dbtbl_master_0
                url: jdbc:mysql://127.0.0.1:3306/dbtbl_0_master?useUnicode=true&characterEncoding=utf-8&useSSL=false
                class: com.mysql.jdbc.Driver
                username: root
                password: mysql
                slaves: jdbc:mysql://127.0.0.1:3306/dbtbl_0_master?useUnicode=true&characterEncoding=utf-8&useSSL=false
            - master:
                name: dbtbl_master_1
                url: jdbc:mysql://127.0.0.1:3306/dbtbl_1_master?useUnicode=true&characterEncoding=utf-8&useSSL=false
                class: com.mysql.jdbc.Driver
                username: root
                password: mysql
                slaves: jdbc:mysql://127.0.0.1:3306/dbtbl_1_master?useUnicode=true&characterEncoding=utf-8&useSSL=false

