#debug: true
server:
  port: 9999
  servlet:
    session:
      cookie:
        name: OAUTH2SESSION

spring:
  profiles: default

management:
  security:
    role: HERO

logging:
  level:
    org.springframework.security: DEBUG
    com.netflix.discovery: 'OFF'

security:
  basic:
    sevlert:
      enabled: false
  oauth2:
    sso:
      loginPath: /dashboard/login
    client:
      clientId: fooClientIdPassword
      clientSecret: secret
      accessTokenUri: http://localhost:8080/oauth/token #是获取访问令牌的URL
      userAuthorizationUri: http://localhost:8080/oauth/authorize #授权用户被重定向的目标URL
      clientAuthenticationScheme: form
    resource:
      userInfoUri: http://localhost:8080/user/me
      preferTokenInfo: false
      jwt:
        key-value: