#debug: true
server:
  port: 9090

spring:
  profiles: default

management:
  security:
    role: HERO

logging:
  level:
    org.springframework.security: DEBUG

jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3307/oauth2?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&tinyInt1isBit=false&useSSL=false
  user: root
  pass: mysql

security:
  oauth2:
    client:
      clientId: fooClientIdPassword
      clientSecret: secret
      accessTokenUri: http://localhost:8080/oauth/token #是获取访问令牌的URL
      userAuthorizationUri: http://localhost:8080/oauth/authorize #授权用户被重定向的目标URL
      scope: foo
      clientAuthenticationScheme: header
    resource:
      user-info-uri: http://localhost:8080/user/me
    authorization:
      check-token-access: http://localhost:8080/oauth/check_token