## 容器
server:
    port: 8080 #启动端口

spring:
  application:
    name: RunningGhost
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true

logging:
       level:
             org.springframework.data: DEBUG
