## 容器
server:
    port: 8080 #启动端口

spring:
  application:
    name: RunningGhost
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 192.168.0.137:9300,192.168.0.137:9302,192.168.0.137:9303
      repositories:
        enabled: true

logging:
       level:
             org.springframework.data: DEBUG
