version: '3.3'

services:
  web:
    build: web
    image: dockerdemos/lab-web
    volumes:
     - "./web/static:/static"
    ports:
     - "8071:80"

  words:
    build: words
    image: dockerdemos/lab-words
    deploy:
      replicas: 2    #创建2个副本
      endpoint_mode: dnsrr
      resources:
        limits:
          memory: 100M #内存太大会被oom而kill
        reservations:
          memory: 10M

  db:
    build: db
    image: dockerdemos/lab-db
